Leila/ram metric 46
max-romagnoli/System-Telemetry-Agent pull request #52
Opened 2024-02-15 00:23 UTC by l3331l4

RAM functions tested and working, also imported functions into exporter.py

2024-02-19 17:47 UTC, max-romagnoli commented
@ljdzed attention needed on this PR.
Need to request change to call method in exporter.py and metrics.py.
Let's try to close it soon, adding at least one or two tests and seeing if Prometheus reads the metrics exposed.

2024-02-20 04:14 UTC, ljdzed requested changes
@max-romagnoli Confirm with Max that prometheus.yml is merged correctly before approval. 

Otherwise good build and good tests added.

2024-02-23 11:16 UTC, max-romagnoli commented
@l3331l4 
Everything looks good. Great job on the tests and connecting your metrics to Prometheus!
This finally closes #15.

I merged dev into this branch to solve any conflict. So I would pull these changes locally and test it yourself with the new docker compose setup (have a look at the `REAMDE_Docker`).

2024-02-23 11:25 UTC, max-romagnoli requested changes

2024-02-23 11:25 UTC, max-romagnoli commented on exporter/metrics.py
> +ram_memory_gauge = Gauge("ram_memory", "Total RAM memory installed")
## Requested Changes
* We need to make the Gauges descriptions more comprehensive. We should include some information on the unit of measure and prefix all of them with the name of our exporter (say `stagent_`). For example:
```suggestion
ram_memory_gauge = Gauge("stagent_ram_memory_bytes", "Total RAM memory installed in bytes")
```

2024-02-23 15:45 UTC, QimingNie approved these changes

2024-02-23 15:47 UTC, QimingNie submitted a review, later dismissed

2024-02-23 16:31 UTC, l3331l4 commented
Tested and working on new docker setup, improved gauge descriptions for RAM metrics.

2024-02-23 22:27 UTC, max-romagnoli approved these changes
# LGTM

2024-02-24 11:30 UTC, merged