Cindy / implement functions to collect networking metrics
max-romagnoli/System-Telemetry-Agent pull request #53
Opened 2024-02-15 09:58 UTC by cindyariyo

Three functions returning inbound traffic, outbound traffic and a string representation of these metrics.

This PR cloes #48.

2024-02-16 11:55 UTC, ljdzed commented on exporter/collectors/network.py
> +network_collector = NetworkCollector()
**Requested Changes**
It seems you've left some of your code from testing in this file. The collector files should not print anything out themselves. Code in Question:

> network_collector = NetworkCollector()
> print(network_collector.__str__())

2024-02-19 17:46 UTC, max-romagnoli commented
@ljdzed attention needed on this PR.
Let's try to close it soon, adding at least one or two tests and seeing if Prometheus reads the metrics exposed.

2024-02-26 14:53 UTC, max-romagnoli commented on tests/exporter/collectors/test_network.py
> +class TestNetworkCollector(unittest.TestCase):
### Requested Changes
* Add the following two tests for the Traffic In and Traffic Out:
  * `test_get_traffic_in_is_not_negative` :  check if method returns >= 0
  * `test_get_traffic_out_is_not_negative` : check if method returns >= 0

2024-02-26 14:54 UTC, max-romagnoli requested changes
@cindyariyo good job with the methods and tests.
I have tested it with Prometheus and the metrics are returned correctly!
I also merged the `dev` into yours to solve any conflict.

You can find comments on two little requested changes. But other than that we should be able to close this today.

2024-02-26 14:55 UTC, max-romagnoli commented on exporter/metrics.py
> +network_get_traffic_out_gauge = Gauge("stagent_traffic_out_mbs", "NETWORK outbound traffic in Mb/s")
### Comment
* Here I have renamed the Gauges to reflect naming conventions.

2024-02-28 15:01 UTC, max-romagnoli approved these changes
# LGTM

2024-02-28 15:43 UTC, merged