Claire/implement CPU metric collection
max-romagnoli/System-Telemetry-Agent pull request #74
Opened 2024-02-26 17:40 UTC by mccooeyc11

Collecting metrics related to the CPU

Known issues:
- The unittest library in Python is refusing to collaborate: fails to recognise tests
- CPU temperature collection with psutil is strange: returns a tuple of temperatures but the location of the CPU temperature within that changes depending on the OS and I'm not sure which it is on our system.

This PR closes #45.

2024-02-28 11:07 UTC, mccooeyc11 commented
Turns out that the final test was failing because I forgot to put an `f` in front of the output string in the method in cpu.py! All of the tests are passing now. I've also added in a 'default' value of 20C in case whatever the collector is running on doesn't expose CPU temperature.

2024-02-28 14:43 UTC, max-romagnoli requested changes
@mccooeyc11 
Good job on the methods and tests! CPU is probably the hardest of the metrics, since data is divided by cores and sensors.

### To close this PR
* See the below requested changes.

### In a next PR
* Return CPU values by core. Probably looping through each core and for each iteration set the Gauges with a new value + label to indicate which core.

2024-02-28 14:43 UTC, max-romagnoli commented on exporter/exporter.py
> +        gauge.set(value)
@mccooeyc11 
I refactored `exporter.py` to check for None values before setting Gauges. This is a sensible thing to do to avoid null pointer errors.

2024-02-28 14:43 UTC, max-romagnoli commented on exporter/metrics.py
> +cpu_temperature_gauge = Gauge("stagent_cpu_coretemp_sensor_1_celsius", "Core temperature from Sensor 1 in Celsius")
@mccooeyc11
I have also refactored the naming and descriptions of Gauges to make them more comprehensive for the frontend to read them.

2024-02-28 14:43 UTC, max-romagnoli commented on exporter/collectors/cpu.py
> +        return psutil.cpu_freq()[0]
### Requested changes
* Accessing the tuple in this way is not clear and could lead to errors. Instead of `[0]` we should use the variable name of the element (like `.current`).
* For reference, here is the tuple: `scpufreq(current=2303.999, min=0.0, max=0.0)`

2024-02-28 14:43 UTC, max-romagnoli commented on exporter/collectors/cpu.py
> +            return psutil.sensors_temperatures()[0][0][1]
### Requested changes
* It's good to check if sensors are None but we should not be returning an arbitrary value like 20.0
* What I would suggest instead is to expand the logic with something like this:
```
# pseudo code

if psutil.sensors_temperatures() is None
      return None

get 'coretemp'

if coretemp has > 0 sensors
      return the first sensor
else return None
```
* I would test the structure of the data by printing stuff to the console of the docker container:
![image](https://github.com/max-romagnoli/System-Telemetry-Agent/assets/68606608/9e612e36-fdee-4fc9-8b12-6511caaebbf2)

2024-02-28 14:43 UTC, max-romagnoli commented on tests/exporter/collectors/test_cpu.py
> +        self.assertTrue(temp <= 100.0)
### Requested Changes
* Refactor temperature test to reflect above changes.

2024-02-29 12:31 UTC, max-romagnoli commented on exporter/collectors/cpu.py
> +                return temps[0].current
Added check `if temps` to ensure that 'acpitz' is not none.

2024-02-29 13:18 UTC, merged